// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToeBlazor.Data;

#nullable disable

namespace TicTacToeBlazorServer.Migrations
{
    [DbContext(typeof(LobbyContext))]
    partial class LobbyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicTacToeBlazor.Models.Lobby", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsWaitingForPlayer")
                        .HasColumnType("bit");

                    b.Property<string>("JoinedPlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("JoinedPlayerId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("TicTacToeBlazor.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TicTacToeBlazor.Models.Lobby", b =>
                {
                    b.HasOne("TicTacToeBlazor.Models.Player", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("TicTacToeBlazor.Models.Player", "JoinedPlayer")
                        .WithMany()
                        .HasForeignKey("JoinedPlayerId");

                    b.Navigation("Creator");

                    b.Navigation("JoinedPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
